config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
   controllers: { registrations: 'users/registrations' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'top#top'
  get 'homes/index'
  get 'musics/search'
  #プロフィールページのルーティング
  get '/users/:id', to: 'users#show', as: 'user'

  resources :posts do
   resources :musics, only: %i(create) do
     get 'search', on: :collection
   end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :post
  validates :tracks, presence: true
  validates :artist, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one :music, dependent: :destroy

  # musicモデルを子モデルとして扱う
  accepts_nested_attributes_for :music
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # アソシエーションを設定
  has_many :posts, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, length: { maximum: 20 }
  validates :profile, length: { maximum: 200 }
  validate :password_complexity

  # 画像のアップローダーを紐付け
  mount_uploader :profile_photo, ProfilePhotoUploader

  def update_without_current_password(params, *options)
    # params.delete(:current_password) で current_password のパラメータを削除
    params.delete(:current_password)

    # パスワード変更のためのパスワード入力フィールドとその確認フィールドの両者とも空の場合のみ、パスワードなしで更新できるようにするためです。
    if params[:password].blank? && params[:password_confirmation]
      params.delete(:password)
      params.delete(:password_confirmation)
    end
    # result = update_attributes(params, *options)はRails6から非推奨の書き方になった
    result = update(params, *options)
    clean_up_passwords
    result
  end

  def password_complexity
    return if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9]).{8,70}$/

    errors.add :password, 'パスワードの強度が不足しています。パスワードの長さは8文字以上とし、大文字と小文字と数をそれぞれ1文字以上含める必要があります。'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  # ログイン後に移動するページを指定
  def after_sign_in_path_for(_resource)
    posts_path
    # user_path(resource)
  end

  # ログアウト後に移動するページを指定
  def after_sign_out_path_for(_resource)
    new_user_session_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name profile profile_photo])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!

  def index; end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  require 'rspotify'
  RSpotify.authenticate(ENV['SPOTIFY_CLIENT_ID'], ENV['SPOTIFY_SECRET_ID'])

  def search
    @musics = RSpotify::Track.search(params[:search]) if params[:search].present?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[show edit update destroy]

  def new
    @post = Post.new
    @post.build_music
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
      flash[:notice] = '投稿が保存されました'
    else
      redirect_to new_post_path
      flash[:alert] = '投稿に失敗しました'
    end
  end

  def index
    @posts = Post.all.includes(:music, :user).order('created_at DESC')
  end

  def show; end

  def edit; end

  def update
    if @post.user == current_user
      flash[:notice] = '投稿を編集しました' if @post.update(post_params)
    else
      flash[:notice] = '投稿の修正に失敗しました'
    end
    redirect_to posts_path
  end

  def destroy
    if @post.user == current_user
      flash[:notice] = '投稿が削除されました' if @post.destroy
    else
      flash[:notice] = '投稿の削除に失敗しました'
    end
    redirect_to posts_path
  end

  private

  # ストロングパラメーターを設定（子モデルの音楽情報と、投稿には文字文章にログインユーザーのidを付与する）
  def post_params
    params.require(:post).permit(
      :text, music_attributes: %i[artist tracks image user_id]
    ).merge(user_id: current_user.id)
  end

  # リファクタリングのためにあらかじめ、対象の投稿を探しておくメソッド
  def set_post
    @post = Post.find_by(id: params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :redirect_index
  def top; end

  private

  def redirect_index
    redirect_to posts_path if user_signed_in?
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  protected

  # パスワードなしでユーザー情報の変更ができる
  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  # ユーザー情報変更後のリダイレクト先を指定
  def after_update_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def profile_photo(user)
    return user.profile_photo unless user.profile_photo.nil?

    user.profile_photo = 'default_icon.jpg'
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<div class="container">
 <div class="row">
   <div class="text-center">
    <h2>このページは仮のトップページです!</h2>
      <% if user_signed_in? %>
        <div class="button-wrap">
          <%= link_to "プロフィール",user_path(current_user), class: "btn btn-primary" %>
        </div>

        <div class="button-wrap">
          <%= link_to "サインアウト",  destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
        </div>
        <p><i class="fab fa-twitter"></i>ここにアイコンを表示</p>


        <%= link_to "検索", musics_search_path %>
<% end %>
    </div>
  </div>
</div>

app/views/top/top.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <!-- -->
  <div class="gtco-container">
<div class="top-img img-responsive">
			<div class="row">
        <div class="col-md-12 col-md-offset-0">
				 <div class="row row-mt-15em">
						<div class="col-md-7 mt-text animate-box" data-animate-effect="fadeInUp">
							<h1>素敵なあの人は今、何を聴いているんだろう？</h1>
              <h2>音楽でゆるく繋がるSNS</h2>

						</div>
						<div class="col-md-4 col-md-push-1 animate-box" data-animate-effect="fadeInRight">
							<div class="form-wrap">
                <!--サインアップ・サインインメニュー -->
								<div class="tab">
									<div class="tab-content">
										<div class="tab-content-inner active" data-content="signup">
											<h3>はじめる</h3>
                      <div class="btn-group-vertical">
                      <%= link_to "新規登録する", new_user_registration_path,  class: "btn btn-success" %>
                      <%= link_to "ログイン", new_user_session_path , class: "btn btn-primary" %>
                      <a href="#" class="btn btn-info">かんたんログイン</a>
                      <a href="#" class="btn btn-info">twitterでログイン</a>
                      <a href="#" class="btn btn-info">googleアカウントでログイン</a>
                      </div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		 </div>
    </div>
</head>

<!-- -->


<body>

  <div id="gtco-features">
		<div class="gtco-container">
			<div class="row">
				<div class="text-center">
					<h2>MusicRecordと音楽でセカイと繋がろう</h2>
					<p>聴いている音楽を投稿するSNSです</p>
				</div>
			</div>
		</div>

    <div class="gtco-container">
			<div class="row">
				<div class="text-center">
					<h2>聴いている音楽を投稿</h2>
					<p>あなたの聴いている音楽を教えてください
          SpotifyやApplemusic,youtubeなどなんでもOKです
         音楽を検索して投稿</p>
				</div>
			</div>
		</div>

    <div class="gtco-container">
			<div class="row">
				<div class="text-center">
					<h2>お気に入りを音楽を紹介</h2>
					<p>プロフィールで影響をうけたアルバム,アーティストを教えてください
          同じものが好きな人がいるかもしれません</p>
				</div>
			</div>
		</div>

    <div class="gtco-container">
      <div class="row">
        <div class="text-center">
          <h2>気になるユーザーをフォロー</h2>
          <p>あの人が何を聴いているか分かります。</p>
        </div>
      </div>
    </div>

    <div class="gtco-container">
			<div class="row">
				<div class="text-center">
					<h2>メッセージで繋がる</h2>
					<p>メッセーのやり取りもできます</p>
				</div>
			</div>
		</div>

  </div>

</body>
</html>