config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
   controllers: { registrations: 'users/registrations' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'top#top'
  get 'homes/index'
  get 'musics/search'
  #プロフィールページのルーティング
  get '/users/:id', to: 'users#show', as: 'user'

  resources :posts do
   resources :musics, only: %i(create) do
     get 'search', on: :collection
   end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one :music, dependent: :destroy

  # musicモデルを子モデルとして扱う
  accepts_nested_attributes_for :music
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[show edit update destroy]

  def new
    @post = Post.new
    @post.build_music
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
      flash[:notice] = '投稿が保存されました'
    else
      redirect_to new_post_path
      flash[:alert] = '投稿に失敗しました'
    end
  end

  def index
    @posts = Post.all.includes(:music, :user).order('created_at DESC')
  end

  def show; end

  def edit; end

  def update
    if @post.user == current_user
      flash[:notice] = '投稿を編集しました' if @post.update(post_params)
    else
      flash[:notice] = '投稿の修正に失敗しました'
    end
    redirect_to posts_path
  end

  def destroy
    if @post.user == current_user
      flash[:notice] = '投稿が削除されました' if @post.destroy
    else
      flash[:notice] = '投稿の削除に失敗しました'
    end
    redirect_to posts_path
  end

  private

  # ストロングパラメーターを設定（子モデルの音楽情報と、投稿には文字文章にログインユーザーのidを付与する）
  def post_params
    params.require(:post).permit(
      :text, music_attributes: %i[artist tracks image user_id]
    ).merge(user_id: current_user.id)
  end

  # リファクタリングのためにあらかじめ、対象の投稿を探しておくメソッド
  def set_post
    @post = Post.find_by(id: params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card ">
    <div class="card bg-secondary">
      <div class="card-header bg-dark">
        Record  音楽を記録しよう
      </div>
            <!--投稿編集部分 -->
        <div class="card-body">
          <div class="container">
            <div class="mt-2">
              <!--ユーザープロフィール画像部分 -->
            <div class="col-auto pr-0">
            <% if current_user.profile_photo? %>
              <img src='<%= current_user.profile_photo %>' class="round-img-nav" size:30 alt="ユーザーアイコン">
            <% else %>
              <img src="<%= asset_path "default_icon.jpg" %>" class="round-img-nav" >
            <% end %>
            </div>
            <!--投稿部分 -->
          <%= form_with model: @post do |f| %>
            <div class="form-group">
            <%= f.text_area :text, class:"form-control", maxlength: "200", rows:"5"  %>
            <!--音楽情報を投稿する部分-->
            <%= f.fields_for :music do |f| %>
              <%= f.label :アーティスト %>
              <%= f.text_field :artist %>

              <%= f.label :曲 %>
              <%= f.text_field :tracks %>
            <% end %>
            <%= f.submit "編集する", class: "btn btn-primary" %>
          <% end %>
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="col-md-8 col-md-2 mx-auto">
    <div class="card-wrap">
      <div class="card bg-secondary">
        <div class="card-header align-items-center d-flex bg-dark">

          <!-- ユーザー画像があれば登録しているユーザー画像、なければデフォルト画像を表示 -->
          <%= link_to user_path(post.user), class: "no-text-decoration" do %>
          <% if post.user.profile_photo? %>
            <img src='<%= post.user.profile_photo %>' class="round-img-nav" size:30 alt="ユーザーアイコン">
          <% else %>
            <img src="<%= asset_path "default_icon.jpg" %>" class="round-img-nav" >
          <% end %>
          <% end %>
          <!-- 投稿したユーザーの名前を表示 -->
          <%= link_to user_path(post.user), class: "no-text-decoration",
            title: post.user.name do %>
            <strong><%= post.user.name %></strong>
          <% end %>
        <!-- 投稿ユーザーの場合、編集・削除アイコンを表示 -->
        <div class="ml-auto">
          <% if post.user_id == current_user.id %>
          <!-- 投稿を編集するアイコン -->
            <div class="post-menu">
              <%= link_to edit_post_path(post) do %>
                 <i class="fas fa-pencil-alt"></i>
              <% end %>
            </div>
            <!-- 投稿を削除するアイコン -->
            <div class="post-menu">
               <%= link_to post_path(post), method: :delete do %>
                 <i class="fas fa-trash"></i>
               <% end %>
             </div>
          <% end %>
        </div>
        </div>
          <!--投稿内容を表示-->
        <div class="text-body">
          <div class="post-text">
            <%= link_to post_path(post), class: "no-text-decoration"  do %>
              <p><%= post.text %></p>
              <!-- 音楽情報を表示 -->
              <%= post.music.tracks %>/<%= post.music.artist %>
            <% end %>
          </div>
        </div>

        <!-- image_tag post.photos.first.image.url(:medium), class: "card-img-top" % -->

        <div class="card-body bg-secondary">
          <div class="row parts">
            <i class="fa fa-heart" aria-hidden="true"></i>
            <!-- %= link_to "", "#", class: "comment" % -->
          </div>
          <div><strong>「いいね！」10件</strong></div>
          <div>
            <span><strong><%= post.user.name %></strong></span>
            <%= link_to time_ago_in_words(post.created_at).upcase + "前", "#", class: "post-time no-text-decoration" %>
            <hr>
            <div class="row parts">
              <form action="#" class="w-100">
                <div>
                  <textarea class="form-control comment-input border-0" placeholder="コメント..." rows="1"></textarea>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card ">
    <div class="card bg-secondary">
      <div class="card-header bg-dark">
        Record  音楽を記録しよう
      </div>
        <div class="card-body">
          <div class="container">
            <div class="mt-2">
              <div class="col-auto pr-0">
            <% if current_user.profile_photo? %>
              <img src='<%= current_user.profile_photo %>' class="round-img-nav" size:30 alt="ユーザーアイコン">
            <% else %>
              <img src="<%= asset_path "default_icon.jpg" %>" class="round-img-nav" >
            <% end %>
            </div>
          <%= form_with model: @post do |f| %>
            <div class="form-group">
            <%= f.text_area :text, class:"form-control", maxlength: "200", rows:"5"  %>
            <!--音楽情報を投稿する部分-->
            <%= f.fields_for :music do |f| %>
              <%= f.label :アーティスト %>
              <%= f.text_field :artist %>

              <%= f.label :曲 %>
              <%= f.text_field :tracks %>
            <% end %>
            <%= f.submit "投稿", class: "btn btn-primary" %>
          <% end %>
           </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="col-md-8 col-md-2 mx-auto">
  <div class="card-wrap">
    <div class="card bg-secondary">
      <div class="card-header align-items-center d-flex bg-dark ">
          <!-- ユーザー画像があれば登録しているユーザー画像、なければデフォルト画像を表示 -->
        <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
        <% if @post.user.profile_photo? %>
          <img src='<%= @post.user.profile_photo %>' class="round-img-nav" size:30 alt="ユーザーアイコン">
        <% else %>
          <img src="<%= asset_path "default_icon.jpg" %>" class="round-img-nav" >
        <% end %>
        <% end %>
        <!-- 投稿したユーザーの名前を表示 -->
        <%= link_to user_path(@post.user), class: "no-text-decoration",
          title: @post.user.name do %>
          <strong><%= @post.user.name %></strong>
        <% end %>

        <!-- 投稿ユーザーの場合、編集・削除アイコンを表示 -->
        <div class="ml-auto">
          <% if @post.user_id == current_user.id %>
          <!-- 投稿を編集するアイコン -->
            <div class="post-menu">
              <%= link_to edit_post_path(@post) do %>
                 <i class="fas fa-pencil-alt"></i>
              <% end %>
            </div>
            <!-- 投稿を削除するアイコン -->
            <div class="post-menu">
               <%= link_to post_path(@post), method: :delete do %>
                 <i class="fas fa-trash"></i>
               <% end %>
             </div>
          <% end %>
        </div>
      </div>
      <!--投稿内容を表示-->
      <div class="text-body">
        <div class="post-text">
      <p><%= @post.text %></p>
      <!-- 音楽情報を表示 -->
      <%= @post.music.tracks %>/<%= @post.music.artist %>
        </div>
      </div>

      <!-- image_tag post.photos.first.image.url(:medium), class: "card-img-top" % -->

      <div class="card-body bg-secondary">
        <div class="row parts">
          <i class="fa fa-heart" aria-hidden="true"></i>
          <!-- %= link_to "", "#", class: "comment" % -->
        </div>
        <div><strong>「いいね！」10件</strong></div>
        <div>
          <span><strong><%= @post.user.name %></strong></span>
          <%= link_to time_ago_in_words(@post.created_at).upcase + "前", "#", class: "post-time no-text-decoration" %>
          <hr>
          <div class="row parts">
            <form action="#" class="w-100">
              <div>
                <textarea class="form-control comment-input border-0" placeholder="コメント..." rows="1"></textarea>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>