config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
   controllers: { registrations: 'users/registrations' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'top#top'
  get 'homes/index'
  get 'musics/search'
  #プロフィールページのルーティング
  get '/users/:id', to: 'users#show', as: 'user'

  resources :posts do
   resources :musics, only: %i(create) do
     get 'search', on: :collection
   end
  end
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :post
  validates :tracks, presence: true
  validates :artist, presence: true
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  require 'rspotify'
  RSpotify.authenticate(ENV['SPOTIFY_CLIENT_ID'], ENV['SPOTIFY_SECRET_ID'])

  def search
    @musics = RSpotify::Track.search(params[:search]) if params[:search].present?
  end
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/musics/search.html.erb
<div class="col-md-8 col-md-2 mx-auto">

<!--検索窓を追加-->
<h3>曲名で検索</h3>
<%= form_with url: search_post_musics_path, method: :get, local: true do |form| %>
<%= form.text_field :search %>
<%= form.submit '曲名検索', name: nil %>

<!--RSpotifyで検索した結果を表示させる-->
  <h1>検索結果</h1>
</div>
  <% if @musics.present? %>
  <% @musics.each do |music| %>
  <div class="col-md-8 col-md-2 mx-auto">
    <div class="music_card">
      <div>
        <%= music.name %> / <%= music.artists.first.name %>
      <% if music.preview_url.present? %>
        <div class="spotify_preview_url">
          <iframe src=<%= music.preview_url %> width="300" height="140"></iframe>
        </div>
      <% end %>
        </div>
        </div>
        </div>
  <% end %>
  <% end %>
<% end %>